### PR TITLE
Fixed decoding fields with 16+ field.length

### PR DESCRIPTION
**Pull request by ZeevM3**
just added an if statement with a counter.

### CODE REVIEW

**Comment by ZeevM3** [comment]
I don't know what the errors mean, anyone?

**Comment by psanford** [comment]
Can you add a test case?

Also please match the formatting used in the rest of the package:
* Spaces instead of tabs
* Change `if(r>=field.length){` to `if (r>=field.length) {`

**Comment by ZeevM3** [comment]
sorry i don't know how to do test case. Can someone send me a link with instructions?

1. spaces instead of tabs <<< what's the significance?
2. what to change i dont understand?

**Comment by psanford** [comment]
You can look at the existing tests for some examples. It looks like you also broke one of the existing tests, so you need to figure out why.

1. Mixing tabs and spaces will make the code appear indented incorrectly in different editors with different settings. Its also just a really bad practice. This repo uses spaces so you will need to switch to spaces for us to accept this patch.

2. You need to make the spacing before and after the parens consistent with the rest of the repository.

**Pull request closed without merging**
