### PR TITLE
Add raw_vendor_attributes property in return packet when decoding.

### PR DESCRIPTION
**Pull request by CodeAnimal**
I haven't added any tests, but it shouldn't fail any current tests.

### CODE REVIEW

**Comment by muirrn** [comment]
Can you help me understand your use case? What is the VSA type/value that wasn't being decoded properly? Or do you not have the dictionary file?

**Comment by CodeAnimal** [comment]
Yeah, I needed the Buffer values of vendor attributes for MS-CHAPv1 and MS-CHAPv2. I have the dictionary file (for vendor ID 311), but the attributes are made up of certain "segments" of data, like the MS-CHAP-Response attribute (https://www.ietf.org/rfc/rfc2548.txt [Section 2.1.3]) or MS-CHAP2-Response attribute (Section 2.3.2).

**Comment by muirrn** [comment]
If you have the dictionary file loaded, the values for those VSAs should already be in the parsed packet as Buffers. They should be under e.g. packet.attributes["Vendor-Specific"]["MS-CHAP2-Response"]. If they aren't there, can you share a sample packet and the dictionary file you are using?

**Comment by CodeAnimal** [comment]
OK, so if I set the ATTRIBUTE in the dictionary to "octets" it works as expected without the vendor raw attributes field. Still might be a useful feature, at least as useful as `raw_attributes` property is. But, granted, after changing the dictionary file it is now not necessary.

**Comment by muirrn** [comment]
Great, I'm glad you got it working. If you have attribute definitions in the dictionary, any type other than "string", "text", "ipaddr", "date", "time" or "integer" will give you a Buffer as the attribute value after parsing. If you don't have the dictionary, you can still manually decode the VSAs out of the normal raw_attributes (they will be inside the value of the VSA attribute in raw_attributes).

**Pull request closed without merging**
